export default () => ({
  name: "store",
  activeScene: "table",
  commands: [],
  question: null,
  commandNames: ["Звездёныши", "Команды", "Помощь", "Выход"],
  table: [
    {
      head: "Head 1",
      body: [
        {
          score: 100,
          text: "text for 1 head",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 200,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 300,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 400,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 500,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 600,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 700,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 800,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
      ],
    },
    {
      head: "Head 2",
      body: [
        {
          score: 100,
          text: "text for 1 head",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 200,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 300,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 400,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 500,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 600,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 700,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 800,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
      ],
    },
    {
      head: "Head 3",
      body: [
        {
          score: 100,
          text: "text for 1 head",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 200,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 300,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 400,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 500,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 600,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 700,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 800,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
      ],
    },
    {
      head: "Head 4",
      body: [
        {
          score: 100,
          text: "text for 1 head",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 200,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 300,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 400,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 500,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 600,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 700,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 800,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
      ],
    },
    {
      head: "Head 5",
      body: [
        {
          score: 100,
          text: "text for 1 head",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 200,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 300,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 400,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 500,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 600,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 700,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 800,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
      ],
    },
    {
      head: "Head 6",
      body: [
        {
          score: 100,
          text: "text for 1 head",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 200,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 300,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 400,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 500,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 600,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 700,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
        {
          score: 800,
          text: "lkldsfj dslk jdsklfjdskl jfkljds",
          isActive: true,
          answer: "answer text",
        },
      ],
    },
  ],
});
